### PR TITLE
localstripe.js: Make compatible with react-stripe-js

### LINKED ISSUE #147: Support for latest stripe-js and react-stripe-js
`react-stripe-js` is doing a validation on the stripe object: https://github.com/stripe/react-stripe-js/blob/e13fae556b1a667a5dfa1130c00d5ec4c2bc154e/src/utils/guards.ts#L16

This validation is failing because of the missing `createPaymentMethod`

### PR DESCRIPTION
**Pull request by brandondyck**
* Add stubbed createPaymentMethod
* Add getElement to elements in JS client
* Fix typo in createToken
* Add unmount and destroy to Element

This fixes #147.

### CODE REVIEW

File: localstripe/localstripe-v3.js [hunk 1]
```diff
@@ -151,17 +164,25 @@ Stripe = (apiKey) => {
   return {
     elements: () => {
       return {
-        create: (type, options) => {
+        create: function(type, options) {
```
Comment (adrienverge) [inline localstripe/localstripe-v3.js:167]: Why going back to the 2nd millennium? :wink: 
(by the way you add an arrow function on line 382).

File: localstripe/localstripe-v3.js [hunk 2]
```diff
@@ -151,17 +164,25 @@ Stripe = (apiKey) => {
...
           console.log('localstripe: Stripe().elements().create()');
-          return new Element();
+          if (this.cardElement) {
+            throw new Error("Can only create one Element of type card");
+          }
+          this.cardElement = new Element(this);
+          return this.cardElement;
         },
+        getElement: function(type) {
```
Comment (adrienverge) [inline localstripe/localstripe-v3.js:175]:
```suggestion
        getElement: type => {
```

File: localstripe/localstripe-v3.js [hunk 3]
```diff
@@ -151,17 +164,25 @@ Stripe = (apiKey) => {
...
+          console.log('localstripe: Stripe().elements().getElement()');
```
Comment (adrienverge) [inline localstripe/localstripe-v3.js:176]: Is this log line very valuable? If not, I'd prefer not spamming the console and remove it.

**Review by adrienverge — COMMENTED** [review]
Thanks for contributing!

This doesn't look bad but I don't understand all the changes. Can you please split each change in an individual commit (easy ones could even be merged in separated PRs, if you'd like), and explain the motivation in each commit message, so reviewers can understand their goal?

For example, I don't get why you add `this.elements` and `this.inputs` to the `Element` class. With real Stripe, they don't seem to exist:
```js
const stripe = Stripe('pk_...');
const element = stripe.elements().create('card');
element.elements  // ← undefined
element.inputs    // ← undefined
```

File: localstripe/localstripe-v3.js (hunk 1 above)
Comment (brandondyck) [reply localstripe/localstripe-v3.js:167]: Because I need to access `this.cardElement`. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), an arrow function "Does not have its own bindings to `this` or `super`, and should not be used as methods."

File: localstripe/localstripe-v3.js (hunk 2 above)
Comment (brandondyck) [reply localstripe/localstripe-v3.js:175]: Same reason as for `elements.create`.

File: localstripe/localstripe-v3.js (hunk 3 above)
Comment (brandondyck) [reply localstripe/localstripe-v3.js:176]: It doesn't matter to me. I was just copying what I saw elsewhere, so I'll take it out.

**Comment by brandondyck** [comment]
> Can you please split each change in an individual commit (easy ones could even be merged in separated PRs, if you'd like), and explain the motivation in each commit message, so reviewers can understand their goal?

Sure, I will split it up and clarify my intent. 🙂

**Comment by brandondyck** [comment]
I've split this up into several commits. The last one is still rather complex, but I don't think there's a reasonable way to avaid that. 🤷 

I also made more changes to fix some problems I found while addressing your comments:
1. I found a bug in the way `mount` was using `document.querySelector`.
2. The `'localstripe:'` span was not being removed by `unmount`.
3. Unexpected sequences of `mount`, `unmount`, and `destroy` calls could leave the elements in an inconsistent state and did not match the behavior of Stripe.js very well, so I introduced a field in `Element` to explicitly track mounting/destruction state. This was kind of a large change, and I'm sorry to give you more work to do after you've already kindly reviewed my PR. 😅  I also hope you don't mind the long essay I wrote in the commit message. 😁

File: localstripe/localstripe-v3.js [hunk 4]
```diff
@@ -357,6 +357,8 @@ Stripe = (apiKey) => {
         }
       }
     },
+
+    createPaymentMethod: async () => ({}),
```
Comment (adrienverge) [inline localstripe/localstripe-v3.js:434]:
```suggestion
    createPaymentMethod: async () => {},
```

File: localstripe/localstripe-v3.js (hunk 1 above)
Comment (adrienverge) [reply localstripe/localstripe-v3.js:221]: > Because I need to access `this.cardElement`.

OK!

> You can blame the JavaScript spec for being inconsistent.

;)

File: localstripe/localstripe-v3.js [hunk 5]
```diff
@@ -80,20 +80,49 @@ function openModal(text, confirmText, cancelText) {
...
+  constructor(elements) {
     this.listeners = {};
+    // Element needs a reference to the object that created it, in order to
+    // thoroughly destroy() itself.
+    this._elements = elements;
   }
 
+  // _state tracks calls to unmount, mount, and destroy, and is always one
+  // of 'unmounted', 'mounted', or 'destroyed'.
+  _state = 'unmounted';
```
Comment (adrienverge) [inline localstripe/localstripe-v3.js:92]: 1. This would probably be better inside the constructor, along with other initializations?
2. It's a bit more complex to maintain 3 states represented as string, and I don't feel `destroyed` + warnings "This Element has already been destroyed..." are very useful.
   A simpler solution would be 2 states with something like `this._mounted` (boolean):
   ```js
     constructor(elements) {
       this.listeners = {};
       // Element needs a reference to the object that created it, in order to
       // thoroughly destroy() itself.
       this._elements = elements;
       this._mounted = false;
     }
   ```
   But in my opinion the best would just be an array `this._htmlChildren = []` (described in my review comment).

File: localstripe/localstripe-v3.js [hunk 6]
```diff
@@ -80,20 +80,49 @@ function openModal(text, confirmText, cancelText) {
 }
 
 class Element {
-  constructor() {
+  constructor(elements) {
     this.listeners = {};
+    // Element needs a reference to the object that created it, in order to
+    // thoroughly destroy() itself.
+    this._elements = elements;
```
Comment (adrienverge) [inline localstripe/localstripe-v3.js:87]: - Much better with a leading `_` for these internal properties :+1: 
- What about `parent` instead of `elements`? It's a bit clearer to me, but this is personal taste. Take the proposal or don't.

File: localstripe/localstripe-v3.js [hunk 7]
```diff
@@ -80,20 +80,49 @@ function openModal(text, confirmText, cancelText) {
...
+  // _state tracks calls to unmount, mount, and destroy, and is always one
+  // of 'unmounted', 'mounted', or 'destroyed'.
+  _state = 'unmounted';
+
   mount(domElement) {
     if (typeof domElement === 'string') {
       domElement = document.querySelector(domElement);
+    } else if (!(domElement instanceof window.Element)) {
+      throw new Error('Invalid DOM element. Make sure to call mount() with ' +
+          'a valid DOM element or selector.');
```
Comment (adrienverge) [inline localstripe/localstripe-v3.js:99]: It's just visual style, but the rest of the file uses this kind of indentation:
```suggestion
      throw new Error('Invalid DOM element. Make sure to call mount() with ' +
                      'a valid DOM element or selector.');
```

**Review by adrienverge — COMMENTED** [review]
Thanks! The commit messages are crystal-clear :ok_hand: 

The 4 first commits are good to go.

About the last one, but I find it a bit complex for what it's doing. Especially maintaining a state (mounted/unmounted) with many inter-related variables: `this._state`, `this._span`, `this._inputs`.
Do you think you could just have one: `this._htmlChildren = []`?
\- if empty → Element is not mounted
\- if has items (span + inputs) → Element is mounted
(and in my opinion we don't have to care about the Element being destroyed twice)

File: localstripe/localstripe-v3.js (hunk 6 above)
Comment (brandondyck) [reply localstripe/localstripe-v3.js]: I think `stripeElements` is clearer than either one. The naming is a little tricky because we are working with both DOM elements and Stripe elements, and the DOM has its own concept of "parent".

**Comment by brandondyck** [comment]
I've simplified `Element` using @adrienverge's idea of keeping an array of children. `Element` no longer matches Stripe's behavior as closely. `mount` still throws an exception if the element has been destroyed, because I think it's important to prevent the broken state of having a duplicate set of input fields with no access to it via `getElement`.

File: localstripe/localstripe-v3.js (hunk 6 above)
Comment (adrienverge) [reply localstripe/localstripe-v3.js]: `this._stripeElements` sound perfect to me :+1:

**Review by adrienverge — APPROVED** [review]
Neat. Thanks for your contribution @brandondyck!
